//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quanlycafenew
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QLCoffeeEntities6 : DbContext
    {
        public QLCoffeeEntities6()
            : base("name=QLCoffeeEntities6")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<tbBan> tbBans { get; set; }
        public virtual DbSet<tbChitiet> tbChitiets { get; set; }
        public virtual DbSet<tbHoadon> tbHoadons { get; set; }
        public virtual DbSet<tbKhachhang> tbKhachhangs { get; set; }
        public virtual DbSet<tbNhanvien> tbNhanviens { get; set; }
        public virtual DbSet<tbSanpham> tbSanphams { get; set; }
    }
}
