//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quanlycafenew
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbBan
    {
        public int ID { get; set; }
        public string TenBan { get; set; }
        public string Trangthai { get; set; }
    }
}
