//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quanlycafenew
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbChitiet
    {
        public int ID { get; set; }
        public Nullable<int> IDHoadon { get; set; }
        public Nullable<int> IDSanpham { get; set; }
        public Nullable<int> IDNhanvien { get; set; }
        public Nullable<int> IDKhachhang { get; set; }
    
        public virtual tbHoadon tbHoadon { get; set; }
        public virtual tbKhachhang tbKhachhang { get; set; }
        public virtual tbNhanvien tbNhanvien { get; set; }
        public virtual tbSanpham tbSanpham { get; set; }
    }
}
