//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quanlycafenew
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbNhanvien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbNhanvien()
        {
            this.tbChitiets = new HashSet<tbChitiet>();
        }
    
        public int ID { get; set; }
        public string TenNV { get; set; }
        public string Ngaysinh { get; set; }
        public string Gioitinh { get; set; }
        public string Quequan { get; set; }
        public string CMND { get; set; }
        public string Email { get; set; }
        public Nullable<int> SDT { get; set; }
        public string Ngaybatdau { get; set; }
        public string Calam { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbChitiet> tbChitiets { get; set; }
    }
}
