//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quanlycafenew
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbSanpham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbSanpham()
        {
            this.tbChitiets = new HashSet<tbChitiet>();
        }
    
        public int ID { get; set; }
        public string TenSP { get; set; }
        public Nullable<int> Dongia { get; set; }
        public Nullable<int> SLTon { get; set; }
        public Nullable<int> SLdaban { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbChitiet> tbChitiets { get; set; }
    }
}
